### PR TITLE
Update 80x

### PR DESCRIPTION
**Pull request by ptraczyk**
updating the package to run in CMSSW_8_0_X by removing the dependence on HiggsAnalysis/CombinedLimit. Two files that were included are now copied over.

### CODE REVIEW

**Comment by usarica** [comment]
Is it possible to remove the ClassImp and ClassDefs? Then there is no need to also put classes.h and the class definitions.

**Comment by ptraczyk** [comment]
I can try to do that, one moment

**Comment by usarica** [comment]
Hi Piotr,

 

Thank you very much for checking this. It would be great if extra dependence on ROOT interpreter  can be avoided.

 

Ulascan

**Comment by ptraczyk** [comment]
I pushed a new commit, it works ok without all these

**Comment by usarica** [comment]
Thank you very much!

**Pull request merged**
