### PR TITLE
Get CMSSW_BASE using getenv

### PR DESCRIPTION
**Pull request by hroskes**
Get CMSSW_BASE using getenv which is needed for crab submission.  This is way more work than it should have been.

It seems that the " character can't be included in the cpp define.  So I next tried
```<flags CPPDEFINES="'_makestringhack_(name)'=#name" />```
since #name makes name into a string.  But # can't be used either.

So I had to resort to getting # indirectly, as you see below. 

It compiles.  I haven't done further tests.

### CODE REVIEW

**Comment by usarica** [comment]
@dsperka @Werbellin Please try this PR. Once we see it works on crab, I will merge this one.

**Comment by Werbellin** [comment]
Excuse my inaptitude, but how do I get the instructions to pull a pending pull request? I can't find the link refereed to by the GitHub help page ?!

**Comment by usarica** [comment]
@Werbellin You can pull the mcfm-hack branch of @hroskes's fork to test. If the commits are successful and we merge, you will have essentially the same content as in master branch of cms-analysis.

**Comment by namapane** [comment]
Or:

git fetch origin pull/[ID]/head:pr-[ID]

where [ID] is the PR number

This puts it in a new branch pr-[ID] so  you also have to

checkout pr-[ID]

n.

**Comment by hroskes** [comment]
There was a bug in what I had last night, I didn't realize that _melapkgpath_ was already turned into a string.  This is fixed now (with small rearranging of C++ code).

**Comment by hroskes** [comment]
I tried [this function](https://github.com/cms-analysis/HiggsAnalysis-ZZMatrixElement/blob/master/MELA/test/testME_v2.c#L26) and it works, so the MCFM symlinks are being made properly.

I think this version should work on crab too, but please let us know when you have a chance to test it.

**Comment by Werbellin** [comment]
Sorry to bother again - I tried the (updated) branch by Heshy. None of them, even the simple recipe by David worked. I always recompiled (scram) the module, but ran from the same cfg. Am I missing something?

**Comment by usarica** [comment]
What is the error you receive? Is it due to MCFM?

**Comment by Werbellin** [comment]
Yes, same error:		
CmsRunFailure
		CMSSW error message follows.
		Fatal Exception
		An exception of category 'PluginLibraryLoadError' occurred while
		   [0] Constructing the EventProcessor
		Exception Message:
		unable to load /scr/u/4248579.bfsrv.jinr-t1.ru/glide_qHqCbD/execute/dir_2644/CMSSW_8_0_26_patch1/lib/slc6_amd64_gcc530/pluginZZAnalysisAnalysisStepPlugins.so because libmcfm_703.so: cannot open shared object file: No such file or directory

**Comment by hroskes** [comment]
I'm not sure if this will work, but maybe try
export LD_LIBRARY_PATH="$CMSSW_BASE/src/ZZMatrixElement/MELA/data/$SCRAM_ARCH:$LD_LIBRARY_PATH"
before doing cmsRun?

**Comment by Werbellin** [comment]
You mean as a custom script on crab? Or on the machine I use to submit?

**Comment by hroskes** [comment]
Um... to be honest I'm not 100% sure how crab works.  Is it simple to add the export to a custom script on crab?

**Comment by Werbellin** [comment]
David pointed me to the extra code needed to get MELA to work on crab. Thanks for the support.

**Comment by namapane** [comment]
@Werbellin, from your output I think your problem is in fact a different one than the one addressed in this PR. The point, I think, is that the absolute path to libmcfm_703.so is hardcoded into pluginZZAnalysisAnalysisStepPlugins.so at compile time. The only way I know to fix this is to declare mcfm as a scram tool. I don't know why it works for David however; David are you handling libmcfm_703.so in any special way?

**Comment by namapane** [comment]
which in fact just instructs cmsenv to setLD_LIBRARY_PATH as suggested by Heshy. I'm not sure if CRAB propagates the local environment from the machine where jobs are submitted or creates a new one using cmsenv, but I think it would be worth trying (ie just set it before submitting crab jobs)

**Comment by usarica** [comment]
Should I go aead and merge this PR, or do we not need it anymore?

**Comment by Werbellin** [comment]
I think having an out-of-the-box way of running MELA on crab, as it is made possible by this PR, is important. Now how this is done under the hood, you guys are the experts :)

**Comment by usarica** [comment]
@Werbellin Would you please be a little bit more clear? Does this PR help solve the some of the issues you see? If so, I will merge this PR. Otherwise, there is no case to merge it.

**Comment by Werbellin** [comment]
The test jobs to see if it works with this PR just finished successfully. Yes please, merge this PR.

**Pull request merged**
